"""Language-neutral generated artifacts shared by framework emitters."""

from __future__ import annotations

import json
from typing import Any, Dict, List

from ..core import IR, camel, pascal, py_type, seed_value, ts_type, zod_expr

GITIGNORE = "node_modules/\ndist/\ncoverage/\n*.log\n__pycache__/\n.venv/\n.env\n"


def ts_models(ir: IR) -> str:
    lines = ["// Generated by BigBack (deterministic; zero tokens)."]
    for ename, values in ir.enums.items():
        lines.append(f"export type {ename} = {' | '.join(json.dumps(v) for v in values)};")
    if ir.enums:
        lines.append("")
    for model in ir.models:
        lines.append(f"export interface {model.name} {{")
        for f in model.fields:
            lines.append(f"  {f.name}: {ts_type(f, ir.enums)};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def ts_zod(ir: IR) -> str:
    lines = [
        "// Generated by BigBack (deterministic; zero tokens).",
        'import { z } from "zod";',
        "",
    ]
    for ename, values in ir.enums.items():
        lines.append(f"export const {ename}Schema = z.enum({json.dumps(values)});")
    if ir.enums:
        lines.append("")
    for model in ir.models:
        c = pascal(model.name)
        fields = [f for f in model.fields if not f.pk]
        lines.append(f"export const {c}CreateSchema = z.object({{")
        for f in fields:
            lines.append(f"  {f.name}: {zod_expr(f, ir.enums)},")
        lines.append("});")
        lines.append(f"export const {c}UpdateSchema = {c}CreateSchema.partial();")
        lines.append(f"export const {c}Schema = {c}CreateSchema.extend({{ id: z.string() }});")
        lines.append(f"export type {c} = z.infer<typeof {c}Schema>;")
        lines.append(f"export type {c}Create = z.infer<typeof {c}CreateSchema>;")
        lines.append(f"export type {c}Update = z.infer<typeof {c}UpdateSchema>;")
        lines.append("")
    return "\n".join(lines)


def ts_store(ir: IR) -> str:
    lines = [
        "// Generated by BigBack (deterministic in-memory store + seed; zero tokens).",
        "export type Row = Record<string, unknown> & { id: string };",
        "",
        "const _tables = new Map<string, Map<string, Row>>();",
        "const _counters = new Map<string, number>();",
        "",
        "function _table(name: string): Map<string, Row> {",
        "  let t = _tables.get(name);",
        "  if (!t) { t = new Map(); _tables.set(name, t); }",
        "  return t;",
        "}",
        "",
        "function _nextId(name: string): string {",
        "  const n = (_counters.get(name) ?? 0) + 1;",
        "  _counters.set(name, n);",
        "  return `${name}_${n}`;",
        "}",
        "",
        "export function list(name: string): Row[] {",
        "  return Array.from(_table(name).values());",
        "}",
        "",
        "export function get(name: string, id: string): Row | undefined {",
        "  return _table(name).get(id);",
        "}",
        "",
        "export function create(name: string, input: Record<string, unknown>): Row {",
        "  const row: Row = { id: _nextId(name), ...input } as Row;",
        "  _table(name).set(row.id, row);",
        "  return row;",
        "}",
        "",
        "export function update(name: string, id: string, patch: Record<string, unknown>): Row | undefined {",
        "  const row = _table(name).get(id);",
        "  if (!row) return undefined;",
        "  const next: Row = { ...row, ...patch, id } as Row;",
        "  _table(name).set(id, next);",
        "  return next;",
        "}",
        "",
        "export function remove(name: string, id: string): boolean {",
        "  return _table(name).delete(id);",
        "}",
        "",
        "export function seed(): void {",
        "  for (const t of _tables.values()) t.clear();",
    ]
    for model in ir.models:
        lname = camel(model.name)
        lines.append("  for (let i = 1; i <= 2; i++) {")
        fields = [f"      {f.name}: {seed_value(f, 'i', ir.enums, 'ts')}" for f in model.fields if not f.pk]
        lines.append(f"    _table({json.dumps(lname)}).set(`{lname}_${{i}}`, {{ id: `{lname}_${{i}}`,")
        lines.append(",\n".join(fields))
        lines.append("    });")
        lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def py_schemas(ir: IR) -> str:
    lines = [
        "from pydantic import BaseModel",
        "from datetime import datetime",
        "from enum import Enum",
        "",
    ]
    for ename, values in ir.enums.items():
        lines.append(f"class {ename}(str, Enum):")
        for v in values:
            lines.append(f"    {v} = {json.dumps(v)}")
        lines.append("")
    for model in ir.models:
        c = pascal(model.name)
        lines.append(f"class {c}Create(BaseModel):")
        for f in model.fields:
            if f.pk:
                continue
            typ = py_type(f, ir.enums)
            if f.optional and not f.list:
                lines.append(f"    {f.name}: {typ} | None = None")
            else:
                lines.append(f"    {f.name}: {typ}")
        lines.append("")
        lines.append(f"class {c}Update(BaseModel):")
        for f in model.fields:
            if f.pk:
                continue
            typ = py_type(f, ir.enums)
            lines.append(f"    {f.name}: {typ} | None = None")
        lines.append("")
        lines.append(f"class {c}({c}Create):")
        lines.append("    id: str")
        lines.append("")
    return "\n".join(lines)


def py_store(ir: IR) -> str:
    lines = [
        '"""Deterministic in-memory store with seeded rows. Zero tokens."""',
        "from __future__ import annotations",
        "from typing import Any",
        "",
        "_tables: dict[str, dict[str, dict[str, Any]]] = {}",
        "_counters: dict[str, int] = {}",
        "",
        "def _table(name: str) -> dict[str, dict[str, Any]]:",
        "    if name not in _tables:",
        "        _tables[name] = {}",
        "    return _tables[name]",
        "",
        "def _next_id(name: str) -> str:",
        "    _counters[name] = _counters.get(name, 0) + 1",
        "    return f'{name}_{_counters[name]}'",
        "",
        "def list_rows(name: str) -> list[dict[str, Any]]:",
        "    return list(_table(name).values())",
        "",
        "def get_row(name: str, row_id: str) -> dict[str, Any] | None:",
        "    return _table(name).get(row_id)",
        "",
        "def create_row(name: str, payload: dict[str, Any]) -> dict[str, Any]:",
        "    row: dict[str, Any] = {'id': _next_id(name), **payload}",
        "    _table(name)[row['id']] = row",
        "    return row",
        "",
        "def update_row(name: str, row_id: str, patch: dict[str, Any]) -> dict[str, Any] | None:",
        "    row = _table(name).get(row_id)",
        "    if row is None:",
        "        return None",
        "    merged = {**row, **patch, 'id': row_id}",
        "    _table(name)[row_id] = merged",
        "    return merged",
        "",
        "def delete_row(name: str, row_id: str) -> bool:",
        "    return _table(name).pop(row_id, None) is not None",
        "",
        "def seed() -> None:",
        "    for t in _tables.values():",
        "        t.clear()",
    ]
    for model in ir.models:
        lname = camel(model.name)
        lines.append("    for i in (1, 2):")
        fields = [f"            '{f.name}': {seed_value(f, 'i', ir.enums, 'py')}" for f in model.fields if not f.pk]
        lines.append(f"        _table({json.dumps(lname)})[f'{lname}_{{i}}'] = {{'id': f'{lname}_{{i}}',")
        lines.append(",\n".join(fields))
        lines.append("        }")
    lines.append("")
    return "\n".join(lines)


def ts_pkg(project: str, deps: Dict[str, str], dev: Dict[str, str], scripts: Dict[str, str]) -> str:
    return json.dumps({
        "name": project,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": scripts,
        "dependencies": deps,
        "devDependencies": dev,
    }, indent=2) + "\n"


def py_reqs(extra: List[str] = None) -> str:
    base = ["pydantic>=2.7"]
    if extra:
        base += extra
    return "\n".join(base) + "\n"


def readme(project: str, framework: str, goal: str) -> str:
    return (
        f"# {project}\n\n"
        f"Backend generated by BigBack (deterministic; zero LLM tokens). Framework: {framework}.\n\n"
        f"Spec: {(goal or '')[:300]}\n"
    )