"""Express (TypeScript) emitter — complete runnable backend from an IR."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ..core import IR, camel, pascal, plural, sample_payload
from ._shared import GITIGNORE, readme, ts_models, ts_store, ts_zod, ts_pkg


def emit(ir: IR, project: str, opts: Optional[Dict[str, Any]] = None) -> tuple[List[Dict[str, str]], List[str]]:
    opts = opts or {}
    auth = bool(opts.get("auth", True))
    health = bool(opts.get("health", True))
    files: List[Dict[str, str]] = []
    notes: List[str] = [
        f"{len(ir.models)} model(s), {len(ir.enums)} enum(s) parsed deterministically.",
        "In-memory store + deterministic seed — runnable with `npm i && npm test`.",
        "DB-ready: connect src/store.ts to Prisma/Drizzle when ready.",
    ]

    def add(path: str, rendered: str) -> None:
        files.append({"output": path, "rendered": rendered})

    add(".gitignore", GITIGNORE)
    add("README.md", readme(project, "express", json.dumps(opts.get("goal", ""))[:300]))
    add("package.json", ts_pkg(
        project,
        {"express": "^4.21.2", "zod": "^3.24.1"},
        {"typescript": "~5.8.2", "vitest": "^4.1.11", "@types/express": "^4.17.21", "@types/node": "^22.0.0", "tsx": "^4.19.0"},
        {"dev": "tsx watch src/server.ts", "build": "tsc", "start": "node dist/server.js",
         "test": "vitest run", "lint": "tsc --noEmit"},
    ))
    add("tsconfig.json", _TSCONFIG)
    add("vitest.config.ts", _VITEST)
    add("src/models.ts", ts_models(ir))
    add("src/zod.ts", ts_zod(ir))
    add("src/store.ts", ts_store(ir))
    add("src/routes.ts", _routes_ts(ir, auth))
    add("src/app.ts", _app_ts(auth))
    add("src/server.ts", _server_ts())
    if auth:
        add("src/security.ts", _security_ts())
    add("src/routes.test.ts", _test_ts(ir, auth, health))
    return files, notes


_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
"""

_VITEST = 'import { defineConfig } from "vitest/config";\n\nexport default defineConfig({ test: { environment: "node" } });\n'


def _security_ts() -> str:
    return (
        'import type { Request, Response, NextFunction } from "express";\n\n'
        "export function requireAuth(req: Request, res: Response, next: NextFunction): void {\n"
        '  const token = process.env.API_TOKEN;\n'
        '  if (!token) { res.status(503).json({ error: "API_TOKEN not configured" }); return; }\n'
        '  if (req.headers.authorization !== `Bearer ${token}`) {\n'
        '    res.status(401).json({ error: "invalid token" }); return;\n'
        "  }\n"
        "  next();\n"
        "}\n"
    )


def _routes_ts(ir: IR, auth: bool) -> str:
    lines = [
        "// Generated by BigBack (deterministic CRUD; zero tokens).",
        'import type { Express, Request, Response } from "express";',
        'import { list, get, create, update, remove } from "./store";',
    ]
    for model in ir.models:
        c = pascal(model.name)
        lines.append(f'import {{ {c}CreateSchema, {c}UpdateSchema }} from "./zod";')
    if auth:
        lines.append('import { requireAuth } from "./security";')
    lines.append("")
    lines.append("export function registerRoutes(app: Express): void {")
    if health := True:
        lines.append('  app.get("/health", (_req: Request, res: Response) => { res.json({ status: "ok" }); });')
    guard = auth
    for model in ir.models:
        c = pascal(model.name)
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        mid = f":id"
        lines.append(f"  app.get({json.dumps(path)}, (_req: Request, res: Response) => {{")
        lines.append(f"    res.json(list({json.dumps(lname)}));")
        lines.append("  });")
        lines.append(f"  app.post({json.dumps(path)}," + (" requireAuth," if guard else "") + " (req: Request, res: Response) => {")
        lines.append(f"    const parsed = {c}CreateSchema.safeParse(req.body);")
        lines.append('    if (!parsed.success) { res.status(400).json({ error: parsed.error.flatten() }); return; }')
        lines.append(f"    res.status(201).json(create({json.dumps(lname)}, parsed.data));")
        lines.append("  });")
        lines.append(f"  app.get({json.dumps(path + '/' + mid)}, (req: Request, res: Response) => {{")
        lines.append(f"    const row = get({json.dumps(lname)}, req.params.id);")
        lines.append('    if (!row) { res.status(404).json({ error: "not found" }); return; }')
        lines.append("    res.json(row);")
        lines.append("  });")
        lines.append(f"  app.put({json.dumps(path + '/' + mid)}," + (" requireAuth," if guard else "") + " (req: Request, res: Response) => {")
        lines.append(f"    const parsed = {c}UpdateSchema.safeParse(req.body);")
        lines.append('    if (!parsed.success) { res.status(400).json({ error: parsed.error.flatten() }); return; }')
        lines.append(f"    const row = update({json.dumps(lname)}, req.params.id, parsed.data);")
        lines.append('    if (!row) { res.status(404).json({ error: "not found" }); return; }')
        lines.append("    res.json(row);")
        lines.append("  });")
        lines.append(f"  app.delete({json.dumps(path + '/' + mid)}," + (" requireAuth," if guard else "") + " (req: Request, res: Response) => {")
        lines.append(f"    if (!remove({json.dumps(lname)}, req.params.id)) {{ res.status(404).json({{ error: \"not found\" }}); return; }}")
        lines.append("    res.status(204).end();")
        lines.append("  });")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _app_ts(auth: bool) -> str:
    lines = [
        'import express from "express";',
        'import type { Express } from "express";',
        'import { registerRoutes } from "./routes";',
    ]
    if auth:
        lines.append('import { requireAuth } from "./security";')
    lines += [
        "",
        "export function createApp(): Express {",
        "  const app = express();",
        "  app.use(express.json());",
    ]
    lines += [
        "  registerRoutes(app);",
        "  return app;",
        "}",
        "",
    ]
    return "\n".join(lines)


def _server_ts() -> str:
    return (
        'import { createApp } from "./app";\n'
        'import type { Express } from "express";\n\n'
        "const app = createApp() as Express;\n"
        "const port = Number(process.env.PORT) || 3000;\n"
        "app.listen(port, () => {\n"
        '  console.log(`api listening on :${port}`);\n'
        "});\n"
    )


def _test_ts(ir: IR, auth: bool, health: bool) -> str:
    lines = [
        "// Generated by BigBack (real integration tests; zero tokens).",
        'import { describe, it, expect, beforeAll, afterAll } from "vitest";',
        'import type { Server } from "node:http";',
        'import { createApp } from "./app";',
        'import { seed } from "./store";',
        "",
        "process.env.API_TOKEN = \"test-token\";",
        "",
        "let server: Server;",
        'let base = "";',
        "",
        'beforeAll(async () => {',
        "  seed();",
        "  server = createApp().listen(0);",
        '  await new Promise((r) => server.once("listening", r));',
        '  const addr = server.address();',
        '  base = `http://127.0.0.1:${typeof addr === "object" && addr ? addr.port : 0}`;',
        "});",
        "",
        'afterAll(() => server?.close());',
        "",
        'describe("crud", () => {',
    ]
    if health:
        lines.append('  it("health", async () => {')
        lines.append('    const res = await fetch(`${base}/health`);')
        lines.append("    expect(res.status).toBe(200);")
        lines.append("  });")
    for model in ir.models:
        c = pascal(model.name)
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        payload = "JSON.stringify({})" if not sample_payload(model, ir.enums, "ts") \
            else "JSON.stringify({ " + ", ".join(sample_payload(model, ir.enums, "ts")) + " })"
        hdr = 'headers: { "Content-Type": "application/json", "Authorization": `Bearer ${process.env.API_TOKEN}` }' if auth \
            else 'headers: { "Content-Type": "application/json" }'
        lines.append(f'  it("{path} create + list + get + update + delete", async () => {{')
        lines.append(f"    const created = await fetch(`${{base}}{path}`, {{ method: \"POST\", {hdr}, body: {payload} }});")
        lines.append("    expect(created.status).toBe(201);")
        lines.append("    const row = (await created.json()) as { id: string };")
        lines.append("    expect(row.id).toBeTruthy();")
        lines.append(f"    const listed = await fetch(`${{base}}{path}`);")
        lines.append("    expect(listed.status).toBe(200);")
        lines.append(f"    const one = await fetch(`${{base}}{path}/${{row.id}}`);")
        lines.append("    expect(one.status).toBe(200);")
        lines.append(f"    const bad = await fetch(`${{base}}{path}/nope`);")
        lines.append("    expect(bad.status).toBe(404);")
        lines.append(f"    const updated = await fetch(`${{base}}{path}/${{row.id}}`, {{ method: \"PUT\", {hdr}, body: JSON.stringify({{}}) }});")
        lines.append("    expect(updated.status).toBe(200);")
        lines.append(f"    const deleted = await fetch(`${{base}}{path}/${{row.id}}`, {{ method: \"DELETE\", {hdr} }});")
        lines.append("    expect(deleted.status).toBe(204);")
        lines.append("  });")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)