"""Fastify (TypeScript) emitter — complete runnable backend."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ..core import IR, camel, pascal, plural, sample_payload
from ._shared import GITIGNORE, readme, ts_models, ts_store, ts_zod, ts_pkg


def emit(ir: IR, project: str, opts: Optional[Dict[str, Any]] = None) -> tuple[List[Dict[str, str]], List[str]]:
    opts = opts or {}
    auth = bool(opts.get("auth", True))
    health = bool(opts.get("health", True))
    files: List[Dict[str, str]] = []
    notes: List[str] = [
        f"{len(ir.models)} model(s), {len(ir.enums)} enum(s) parsed deterministically.",
        "Fastify is schema-first (JSON Schema under the hood); zod used here for runtime validation.",
    ]

    def add(path: str, rendered: str) -> None:
        files.append({"output": path, "rendered": rendered})

    add(".gitignore", GITIGNORE)
    add("README.md", readme(project, "fastify", json.dumps(opts.get("goal", ""))[:300]))
    add("package.json", ts_pkg(
        project,
        {"fastify": "^5.0.0", "zod": "^3.24.1"},
        {"typescript": "~5.8.2", "vitest": "^4.1.11", "@types/node": "^22.0.0"},
        {"dev": "tsx watch src/server.ts", "build": "tsc", "start": "node dist/server.js",
         "test": "vitest run", "lint": "tsc --noEmit"},
    ))
    add("tsconfig.json", _TSCONFIG)
    add("vitest.config.ts", _VITEST)
    add("src/models.ts", ts_models(ir))
    add("src/zod.ts", ts_zod(ir))
    add("src/store.ts", ts_store(ir))
    add("src/app.ts", _app_ts(ir, auth, health))
    add("src/server.ts", _server_ts())
    add("src/app.test.ts", _test_ts(ir, auth, health))
    return files, notes


_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
"""

_VITEST = 'import { defineConfig } from "vitest/config";\n\nexport default defineConfig({ test: { environment: "node" } });\n'


def _app_ts(ir: IR, auth: bool, health: bool) -> str:
    lines = [
        "// Generated by BigBack (deterministic CRUD; zero tokens).",
        'import Fastify, { FastifyInstance } from "fastify";',
        'import { list, get, create, update, remove, seed } from "./store";',
    ]
    for model in ir.models:
        c = pascal(model.name)
        lines.append(f'import {{ {c}CreateSchema, {c}UpdateSchema }} from "./zod";')
    lines += [
        "",
        "export async function createApp(): Promise<FastifyInstance> {",
        "  const app = Fastify({ logger: false });",
    ]
    if health:
        lines.append('  app.get("/health", async () => ({ status: "ok" }));')
    for model in ir.models:
        c = pascal(model.name)
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        lines.append(f"  app.get({json.dumps(path)}, async () => list({json.dumps(lname)}));")
        lines.append(f"  app.post({json.dumps(path)}, async (req, reply) => {{")
        lines.append(f"    const parsed = {c}CreateSchema.safeParse(req.body);")
        lines.append("    if (!parsed.success) return reply.code(400).send({ error: parsed.error.flatten() });")
        lines.append(f"    return reply.code(201).send(create({json.dumps(lname)}, parsed.data));")
        lines.append("  });")
        lines.append(f"  app.get({json.dumps(path + '/:id')}, async (req, reply) => {{")
        lines.append(f"    const row = get({json.dumps(lname)}, (req.params as {{ id: string }}).id);")
        lines.append("    if (!row) return reply.code(404).send({ error: \"not found\" });")
        lines.append("    return row;")
        lines.append("  });")
        lines.append(f"  app.put({json.dumps(path + '/:id')}, async (req, reply) => {{")
        lines.append(f"    const parsed = {c}UpdateSchema.safeParse(req.body);")
        lines.append("    if (!parsed.success) return reply.code(400).send({ error: parsed.error.flatten() });")
        lines.append(f"    const row = update({json.dumps(lname)}, (req.params as {{ id: string }}).id, parsed.data);")
        lines.append("    if (!row) return reply.code(404).send({ error: \"not found\" });")
        lines.append("    return row;")
        lines.append("  });")
        lines.append(f"  app.delete({json.dumps(path + '/:id')}, async (req, reply) => {{")
        lines.append(f"    if (!remove({json.dumps(lname)}, (req.params as {{ id: string }}).id)) return reply.code(404).send({{ error: \"not found\" }});")
        lines.append("    return reply.code(204).send();")
        lines.append("  });")
    if auth:
        lines += [
            "",
            "  // Write-guard: Bearer token from API_TOKEN env.",
            "  app.addHook(\"preHandler\", async (req, reply) => {",
            '    if (req.method === "GET") return;',
            "    const token = process.env.API_TOKEN;",
            '    if (!token) return reply.code(503).send({ error: "API_TOKEN not configured" });',
            '    if (req.headers.authorization !== `Bearer ${token}`) return reply.code(401).send({ error: "invalid token" });',
            "  });",
        ]
    lines += ["  return app;", "}", ""]
    return "\n".join(lines)


def _server_ts() -> str:
    return (
        'import { createApp } from "./app";\n\n'
        "const app = await createApp();\n"
        "const port = Number(process.env.PORT) || 3000;\n"
        "await app.listen({ port, host: \"0.0.0.0\" });\n"
        'console.log(`api listening on :${port}`);\n'
    )


def _test_ts(ir: IR, auth: bool, health: bool) -> str:
    lines = [
        "// Generated by BigBack (real integration tests; zero tokens).",
        'import { describe, it, expect, beforeAll, afterAll } from "vitest";',
        'import type { FastifyInstance } from "fastify";',
        'import { createApp } from "./app";',
        'import { seed } from "./store";',
        "",
        "process.env.API_TOKEN = \"test-token\";",
        "let app: FastifyInstance;",
        'const auth = { Authorization: `Bearer ${process.env.API_TOKEN}` };',
        'const json = { "Content-Type": "application/json", Authorization: `Bearer ${process.env.API_TOKEN}` };',
        "",
        'beforeAll(async () => { app = await createApp(); seed(); await app.ready(); });',
        'afterAll(() => app.close());',
        "",
        'describe("crud", () => {',
    ]
    if health:
        lines.append('  it("health", async () => {')
        lines.append('    const res = await app.inject({ method: "GET", url: "/health" });')
        lines.append("    expect(res.statusCode).toBe(200);")
        lines.append("  });")
    for model in ir.models:
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        payload = "{}" if not sample_payload(model, ir.enums, "ts") \
            else "{ " + ", ".join(sample_payload(model, ir.enums, "ts")) + " }"
        body = f"JSON.stringify({payload})"
        lines.append(f'  it("{path} create + list + get + update + delete", async () => {{')
        lines.append(f"    const created = await app.inject({{ method: \"POST\", url: {json.dumps(path)}, headers: json, payload: {body} }});")
        lines.append("    expect(created.statusCode).toBe(201);")
        lines.append("    const row = created.json() as { id: string };")
        lines.append("    expect(row.id).toBeTruthy();")
        lines.append(f"    expect((await app.inject({{ method: \"GET\", url: {json.dumps(path)} }})).statusCode).toBe(200);")
        lines.append(f"    expect((await app.inject({{ method: \"GET\", url: {json.dumps(path)} + '/' + row.id }})).statusCode).toBe(200);")
        lines.append(f"    expect((await app.inject({{ method: \"GET\", url: {json.dumps(path + '/nope')} }})).statusCode).toBe(404);")
        lines.append(f"    const updated = await app.inject({{ method: \"PUT\", url: {json.dumps(path)} + '/' + row.id, headers: json, payload: JSON.stringify({{}}) }});")
        lines.append("    expect(updated.statusCode).toBe(200);")
        lines.append(f"    const deleted = await app.inject({{ method: \"DELETE\", url: {json.dumps(path)} + '/' + row.id, headers: auth }});")
        lines.append("    expect(deleted.statusCode).toBe(204);")
        lines.append("  });")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)