"""Hono (TypeScript, edge-friendly) emitter — complete runnable backend."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ..core import IR, camel, pascal, plural, sample_payload
from ._shared import GITIGNORE, readme, ts_models, ts_store, ts_zod, ts_pkg


def emit(ir: IR, project: str, opts: Optional[Dict[str, Any]] = None) -> tuple[List[Dict[str, str]], List[str]]:
    opts = opts or {}
    auth = bool(opts.get("auth", True))
    health = bool(opts.get("health", True))
    files: List[Dict[str, str]] = []
    notes: List[str] = [
        f"{len(ir.models)} model(s), {len(ir.enums)} enum(s) parsed deterministically.",
        "Hono runs on Node, Deno, Bun and edge runtimes — test with `npm i && npm test`.",
    ]

    def add(path: str, rendered: str) -> None:
        files.append({"output": path, "rendered": rendered})

    add(".gitignore", GITIGNORE)
    add("README.md", readme(project, "hono", json.dumps(opts.get("goal", ""))[:300]))
    add("package.json", ts_pkg(
        project,
        {"hono": "^4.6.0", "zod": "^3.24.1", "@hono/node-server": "^1.13.0"},
        {"typescript": "~5.8.2", "vitest": "^4.1.11", "@types/node": "^22.0.0"},
        {"dev": "tsx watch src/server.ts", "build": "tsc", "start": "node dist/server.js",
         "test": "vitest run", "lint": "tsc --noEmit"},
    ))
    add("tsconfig.json", _TSCONFIG)
    add("vitest.config.ts", _VITEST)
    add("src/models.ts", ts_models(ir))
    add("src/zod.ts", ts_zod(ir))
    add("src/store.ts", ts_store(ir))
    add("src/app.ts", _app_ts(ir, auth, health))
    add("src/server.ts", _server_ts())
    add("src/app.test.ts", _test_ts(ir, auth, health))
    return files, notes


_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
"""

_VITEST = 'import { defineConfig } from "vitest/config";\n\nexport default defineConfig({ test: { environment: "node" } });\n'


def _app_ts(ir: IR, auth: bool, health: bool) -> str:
    lines = [
        "// Generated by BigBack (deterministic CRUD; zero tokens).",
        'import { Hono } from "hono";',
        'import { list, get, create, update, remove, seed } from "./store";',
    ]
    for model in ir.models:
        c = pascal(model.name)
        lines.append(f'import {{ {c}CreateSchema, {c}UpdateSchema }} from "./zod";')
    lines += ["", "export function createApp(): Hono {", "  const app = new Hono();"]
    if health:
        lines.append('  app.get("/health", (c) => c.json({ status: "ok" }));')
    for model in ir.models:
        c = pascal(model.name)
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        lines.append(f"  app.get({json.dumps(path)}, (c) => c.json(list({json.dumps(lname)})));")
        lines.append(f"  app.post({json.dumps(path)}, async (c) => {{")
        lines.append("    const body = await c.req.json().catch(() => null);")
        lines.append(f"    const parsed = {c}CreateSchema.safeParse(body);")
        lines.append("    if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);")
        lines.append(f"    return c.json(create({json.dumps(lname)}, parsed.data), 201);")
        lines.append("  });")
        lines.append(f"  app.get({json.dumps(path + '/:id')}, (c) => {{")
        lines.append(f"    const row = get({json.dumps(lname)}, c.req.param(\"id\"));")
        lines.append("    if (!row) return c.json({ error: \"not found\" }, 404);")
        lines.append("    return c.json(row);")
        lines.append("  });")
        lines.append(f"  app.put({json.dumps(path + '/:id')}, async (c) => {{")
        lines.append("    const body = await c.req.json().catch(() => null);")
        lines.append(f"    const parsed = {c}UpdateSchema.safeParse(body);")
        lines.append("    if (!parsed.success) return c.json({ error: parsed.error.flatten() }, 400);")
        lines.append(f"    const row = update({json.dumps(lname)}, c.req.param(\"id\"), parsed.data);")
        lines.append("    if (!row) return c.json({ error: \"not found\" }, 404);")
        lines.append("    return c.json(row);")
        lines.append("  });")
        lines.append(f"  app.delete({json.dumps(path + '/:id')}, (c) => {{")
        lines.append(f"    if (!remove({json.dumps(lname)}, c.req.param(\"id\"))) return c.json({{ error: \"not found\" }}, 404);")
        lines.append("    return c.body(null, 204);")
        lines.append("  });")
    if auth:
        lines += [
            "",
            "  // Write-guard: Bearer token from API_TOKEN env.",
            "  app.use(\"*\", async (c, next) => {",
            "    const token = process.env.API_TOKEN;",
            '    if (c.req.method === "GET") return next();',
            "    if (!token) return c.json({ error: \"API_TOKEN not configured\" }, 503);",
            '    if (c.req.header("Authorization") !== `Bearer ${token}`) return c.json({ error: "invalid token" }, 401);',
            "    return next();",
            "  });",
        ]
    lines += ["  return app;", "}", ""]
    return "\n".join(lines)


def _server_ts() -> str:
    return (
        'import { serve } from "@hono/node-server";\n'
        'import { createApp } from "./app";\n\n'
        "const app = createApp();\n"
        "const port = Number(process.env.PORT) || 3000;\n"
        "serve({ fetch: app.fetch, port }, (info) => {\n"
        '  console.log(`api listening on :${info.port}`);\n'
        "});\n"
    )


def _test_ts(ir: IR, auth: bool, health: bool) -> str:
    lines = [
        "// Generated by BigBack (real integration tests; zero tokens).",
        'import { describe, it, expect, beforeAll } from "vitest";',
        'import { createApp } from "./app";',
        'import { seed } from "./store";',
        "",
        "process.env.API_TOKEN = \"test-token\";",
        "const app = createApp();",
        "const hdr = () => ({ \"Content-Type\": \"application/json\", Authorization: `Bearer ${process.env.API_TOKEN}` });",
        "",
        'beforeAll(() => seed());',
        "",
        'describe("crud", () => {',
    ]
    if health:
        lines.append('  it("health", async () => {')
        lines.append('    const res = await app.request("/health");')
        lines.append("    expect(res.status).toBe(200);")
        lines.append("  });")
    for model in ir.models:
        lname = camel(model.name)
        path = f"/{plural(lname)}"
        payload = "{}" if not sample_payload(model, ir.enums, "ts") \
            else "{ " + ", ".join(sample_payload(model, ir.enums, "ts")) + " }"
        body = f"JSON.stringify({payload})"
        lines.append(f'  it("{path} create + list + get + update + delete", async () => {{')
        lines.append(f"    const created = await app.request({json.dumps(path)}, {{ method: \"POST\", headers: hdr(), body: {body} }});")
        lines.append("    expect(created.status).toBe(201);")
        lines.append("    const row = (await created.json()) as { id: string };")
        lines.append("    expect(row.id).toBeTruthy();")
        lines.append(f"    expect((await app.request({json.dumps(path)})).status).toBe(200);")
        lines.append(f"    expect((await app.request({json.dumps(path + '/')} + row.id)).status).toBe(200);")
        lines.append(f"    expect((await app.request({json.dumps(path + '/nope')})).status).toBe(404);")
        lines.append(f"    const updated = await app.request({json.dumps(path + '/')} + row.id, {{ method: \"PUT\", headers: hdr(), body: JSON.stringify({{}}) }});")
        lines.append("    expect(updated.status).toBe(200);")
        lines.append(f"    const deleted = await app.request({json.dumps(path + '/')} + row.id, {{ method: \"DELETE\", headers: hdr() }});")
        lines.append("    expect(deleted.status).toBe(204);")
        lines.append("  });")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)